spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/springsecurity
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to Spring Security Api!!